# Description : docker-compose.base.yml - ğŸ“Œ Docker ì‹¤í–‰ í™˜ê²½ ì •ì˜ íŒŒì¼
# Date : 2025-04-10

networks:
  app_network:
    driver: bridge

volumes:
  common_data:
    driver: local

services:
  # ê³µí†µ íŒ¨í‚¤ì§€ ì»¨í…Œì´ë„ˆ
  common:
    build:
      context: .
      dockerfile: ./common/Dockerfile
    image: common:latest
    container_name: common
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - common_data:/app/common
    working_dir: /app/common
    command: ['tail', '-f', '/dev/null']

